# Generated by Django 4.0.5 on 2022-07-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thread',
            new_name='Topic',
        ),
    ]
