# Generated by Django 4.0.5 on 2022-07-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_thread_post_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Topic',
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
