# Generated by Django 4.0.5 on 2022-07-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
