# Generated by Django 4.0.5 on 2022-07-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_counterpost_created_by_counterpost_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterpost',
            name='created_by',
        ),
        migrations.AddField(
            model_name='counterpost',
            name='created_by',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.RemoveField(
            model_name='counterpost',
            name='seeds',
        ),
        migrations.AddField(
            model_name='counterpost',
            name='seeds',
            field=models.ManyToManyField(blank=True, related_name='seeds', to='accounts.profile'),
        ),
    ]
