# Generated by Django 4.0.5 on 2022-07-02 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_counterpost_created_by_counterpost_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='seeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CounterPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterpost', to='accounts.counterpost')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.profile')),
            ],
        ),
    ]
