# Generated by Django 4.0.5 on 2022-07-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seeds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterpost',
            name='seeds',
        ),
        migrations.AddField(
            model_name='counterpost',
            name='seeds',
            field=models.IntegerField(null=True),
        ),
    ]
