# Generated by Django 4.0.5 on 2022-07-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_counterpost_seeds_counterpost_seeds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeds',
            name='CounterPost',
        ),
        migrations.RemoveField(
            model_name='seeds',
            name='Profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='flags',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='postList',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='seeds',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='CounterPost',
        ),
        migrations.DeleteModel(
            name='seeds',
        ),
    ]
