# Generated by Django 4.0.5 on 2022-07-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_seeds_counterpost_remove_seeds_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='flags',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postList',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='seeds',
            field=models.IntegerField(null=True),
        ),
    ]
